#!/bin/bash


case "$1" in
  server)
    ./daolinet --debug server --listen :808 --swarm tcp://192.168.135.128:3376 etcd://192.168.135.128:4001
  ;;
  agent)
    ./daolinet agent --int-nic eno16777736:192.168.135.128 etcd://192.168.135.128:4001
  ;;
  *)
    echo "usage: $0 <server|agent>"
esac
